### ISSUE TITLE
tedana.py v2.5 fails with large images - update to v3.2

### ISSUE THREAD

**Issue by dpark6060** [afni/afni#346]
This is a request to update the default meica.libs/tedana.py from the current version included in AFNI (v2.5) to the latest release (v3.1) because of better handling of saving large outputs.

When installing afni the recommended way, as [instructed on your site for ubuntu 18](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu18.html)

I noticed that the "tedana.py" in `abin/meica.libs/tedana.py` is version `v2.5 beta11`, while the last update [to the old repository ](https://github.com/ME-ICA/me-ica/blob/master/meica.libs/tedana.py) is `v3.2 beta1`.  If afni is not going to switch to the newer, supported tedana repo, I would request that they update their current me-ica.libs to the updated version of this repository.  

The reason for this is because the v2.5 tedana uses a chain of libraries that fails when saving large python variables (~500Mb or more).  We currently have multi echo fMRI data that is very high resolution, and the `pcastate` variable it tries to save is almost 1Gb.  line 428/429 in the old version use cPickle and bz2:

```
  pcastate_f = bz2.BZ2File('pcastate.pklbz','wb')
  pickle.dump(pcastate,pcastate_f)
```

for some reason this combination errors with large arrays:

```
Traceback (most recent call last):
  File "/root/abin/meica.libs/tedana.py", line 688, in <module>
    nc,dd = tedpca(options.ste)
  File "/root/abin/meica.libs/tedana.py", line 429, in tedpca
    pickle.dump(pcastate,pcastate_f)
ValueError: the bz2 library has received wrong parameters 
```
 (I verified that I get this error trying to save outside of tedana and with multiple kinds of data)

The latest version of tedana.py (v3.2) uses a [different method to save the data](https://github.com/ME-ICA/me-ica/blob/master/meica.libs/tedana.py#L570):

```
pcastate_f = gzip.open(pcastate_fn,'wb')
pickle.dump(pcastate,pcastate_f)
```

Which I have verified DOES work with large data.

**Comment by afni-rickr** [comment]
Hi @dpark6060.  The form of tedana.py that is being distributed with AFNI is a convenience for current users of it.  The more modern version of tedana also works very well with AFNI (with afni_proc.py in particular), but we have no intention of distributing it.  Rather, once people are basically done using the old version, we will cease to distribute any version at all.
So please feel free to use the newer version, indeed, it has many nice features.

**Comment by jbteves** [comment]
@dpark6060 let me know if you have any issues installing the new version of tedana. Please see the documentation [here](https://tedana.readthedocs.io/en/stable/). In an existing `afni_proc`, you can use the new tedana version with `m_tedana` instead of `tedana` ("my" tedana). Be advised that the outputs have changed considerably.

**Comment by mrneont** [comment]
@dpark6060 :  Do you have any other questions/comments about this?  If not, I will close this issue.

**Comment by dpark6060** [comment]
Yes.  So I can simply replace tedana.py with the new one, and it will work with no modification required to afni_proc?  If so, yes this can be closed, thank you.

**Comment by mrneont** [comment]
I think the best thing might be to check out the new `afni_proc.py` multiecho processing demo, which can be downloaded+unpacked with: 
`@Install_APMULTI_Demo1_rest`

It gives examples of tweaking one `afni_proc.py` command for various processing cases, including several multiecho processing/combination methods (the older MEICA, from Kundu et al.; the newer tedana from the MEICA group;  optimally combined, from Posse et al.).  It also shows how one can include blip up/down distortion correction, surface projection, physio regressors and nonlinear warping.  

From the end of README_process.txt:

```
----------------------------------------------------------------------
The description of the script file naming is in README.txt.

Any of the run_LABEL.tcsh scripts can be run (on biowulf or a desktop)
to perform the given LABEL step.  The result would be a data_LABEL
directory (where LABEL would be 26_ap_me_bT in the above example).

Here is the list of run_* scripts (under scripts_biowulf or scripts_desktop),
with any comments for extra software considerations (besides AFNI).

   * Prantik's tedana comes with AFNI
   * MEICA tedana must be installed separately, with 'tedana' in the PATH
     - see https://tedana.readthedocs.io/en/stable/installation.html
   * FreeSurfer must be installed separately
     - see https://surfer.nmr.mgh.harvard.edu


   processing script            processing requirements (besides AFNI)
   -----------------            --------------------------------------
   run_12_fs.tcsh               requires FreeSurfer
   run_13_ssw.tcsh
   run_14_physio.tcsh
   run_20_ap_se.tcsh
   run_21_ap_me.tcsh
   run_22_ap_me_b.tcsh
   run_23_ap_me_bt.tcsh         Prantik's tedana.py requires python 2.7
   run_24_ap_me_bts.tcsh        Prantik's tedana.py requires python 2.7
   run_25_ap_me_br.tcsh
   run_26_ap_me_bT.tcsh         MEICA tedana requires 'tedana' and python 3.6+
   run_30_ap_se_n.tcsh
   run_33_ap_me_btn.tcsh        Prantik's tedana.py requires python 2.7
   run_36_ap_me_bTn.tcsh        MEICA tedana requires 'tedana' and python 3.6+
```
... so you would want the scripts with "T" in them (those use the MEICA-group tedana), assuming you have installed it already.

**Comment by dpark6060** [comment]
Thank you very much for this detailed and helpful reply.  You can consider this closed.

**Comment by mrneont** [comment]
Cool, feel free to ask further questions here or on the Message Board: 
https://afni.nimh.nih.gov/afni/community/board/list.php?1
