### ISSUE TITLE
CircleCI test_cmake_build is failing on tests which blocks other stages

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni#651]
![image](https://github.com/afni/afni/assets/39889/f89ee5ce-4a94-4805-9854-7f2a22c12771)

and (one of) the reason(s) seems to be just inability to get some annexed file

```
  File "/opt/user_pip_packages/lib/python3.6/site-packages/datalad/distribution/dataset.py", line 484, in apply_func

    return f(**kwargs)

  File "/opt/user_pip_packages/lib/python3.6/site-packages/datalad/interface/utils.py", line 484, in eval_func

    return return_func(generator_func)(*args, **kwargs)

  File "/opt/user_pip_packages/lib/python3.6/site-packages/datalad/interface/utils.py", line 476, in return_func

    results = list(results)

  File "/opt/user_pip_packages/lib/python3.6/site-packages/datalad/interface/utils.py", line 463, in generator_func

    msg="Command did not complete successfully")

datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 2 failed:

[{'action': 'get',

  'annexkey': 'MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK',

  'error_message': 'download failed: Not Found\n'

                   'failed to download content\n'

                   'download failed: Not Found\n'

                   'failed to download content\n'

                   'download failed: Not Found\n'

                   'failed to download content',

  'path': '/opt/****/src/tests/****_ci_test_data/AFNI_data6/****/epi_r1+orig.BRIK',

  'refds': '/opt/****/src/tests/****_ci_test_data',

  'status': 'error',

  'type': 'file'},
```

interestingly `git-annex` knows that this key was available from the data repository 

```
❯ git annex whereis --key MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK
(merging origin/git-annex into git-annex...)
(recording state in git...)
whereis MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK (21 copies) 
  	1e7f292a-1334-46ac-a370-7a95c043bede -- rodgersleejg@promethium.nimh.nih.gov:~/afni_ci_test_data
...
   	b63ca06b-cbad-4f68-85e3-4a62b5dd9f23 -- rodgersleejg@promethium.nimh.nih.gov:/store/data/rodgersleejg/afni_ci_test_data
   	c1ce38d5-c2ef-48c6-a1f2-e207215d0717 -- AFNI server for storing data for cheap. Not always available and requires ssh key to upload though. [afni_ci_test_data]
ok
```

but when I actually try to get it -- it realizes that is no longer there unfortunately (  I guess was removed):

```
... TODO... more to find/paste
```

**Comment by mrneont** [comment]
@yarikoptic : indeed, this has been on our "to do" list for a while.  We weren't sure if were due to a server crash we had a while back, or to CircleCI forced updates, or to both.  Then we just got distracted by other projects.  Sigh.

**Comment by yarikoptic** [comment]
does anyone have a copy of that file which could still be shared ?  `annex whereis` lists plenty of locations ! ;-)

**Comment by yarikoptic** [comment]
would be happy to jump on zoom to guide/assist if needed

**Comment by afni-rickr** [comment]
Hi @yarikoptic.  We did find that file, and it seems to be exactly the distributed [epi_r1+orig.BRIK](https://afni.nimh.nih.gov/pub/dist/edu/data/CD.expanded/AFNI_data6/afni/epi_r1+orig.BRIK).  It seemed unlikely that just one file got lost from the annex tree when our disk had to be rebuilt, so the expectation has been that it's a bigger issue, but maybe not.
We did find that file in an annex tree, if that would be the most straightforward way to restore it.  Thanks!

**Comment by yarikoptic** [comment]
well, that is odd

```shell
❯ git fetch afni_ci_test_data
From https://afni.nimh.nih.gov/pub/dist/data/afni_ci_test_data/
   d6b2c78d0..023b5d9bf  git-annex  -> afni_ci_test_data/git-annex
   d244723ac..df42c5b16  master     -> afni_ci_test_data/master
❯ git annex get --key MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK
get MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK (from afni_ci_test_data...) 

  download failed: Not Found

  failed to download content

  Unable to access these remotes: afni_ci_test_data
...
```

<details>
<summary>file is really not there yet</summary> 

```shell
❯ git annex --debug get --from afni_ci_test_data --key MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK
[2024-06-05 22:03:39.697892806] (Utility.Process) process [1004806] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2024-06-05 22:03:39.701657065] (Utility.Process) process [1004806] done ExitSuccess
[2024-06-05 22:03:39.70269606] (Utility.Process) process [1004807] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2024-06-05 22:03:39.705961764] (Utility.Process) process [1004807] done ExitSuccess
[2024-06-05 22:03:39.708307087] (Utility.Process) process [1004808] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
get MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK (from afni_ci_test_data...) [2024-06-05 22:03:39.72182972] (Utility.Process) process [1004808] done ExitSuccess

[2024-06-05 22:03:39.758751627] (Utility.Url) Request {
  host                 = "afni.nimh.nih.gov"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding","identity"),("User-Agent","git-annex/10.20240129")]
  path                 = "/pub/dist/data/afni_ci_test_data/.git/annex/objects/7w/kX/MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK/MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}

[2024-06-05 22:03:40.175221412] (Utility.Url) Request {
  host                 = "afni.nimh.nih.gov"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding","identity"),("User-Agent","git-annex/10.20240129")]
  path                 = "/pub/dist/data/afni_ci_test_data/.git/annex/objects/f18/9b9/MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK/MD5E-s64204800--a148018677aff4268af57f2f32eec46c.BRIK"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}


  download failed: Not Found

  failed to download content
failed
get: 1 failed

```
</details>

buzz me when it gets there plz

**Comment by mrneont** [comment]
I feel sheepish for asking, but how should I do that here?  

When I look at the contents of 
```
$ ls -1
anat+orig.HEAD
anat+tlrc.HEAD
AV_r1.make_reg.tcsh
epi_r1_cleanup
epi_r1_ideal.1D
epi_r1_regress
epi_r1_times.txt
index.html
mask.auto.nii.gz
mask.left.vis.aud+orig.BRIK.gz
mask.left.vis.aud+orig.HEAD
quick.r1_times.txt
quick.s1.afni_proc
quick.s9.cleanup
rall_cleanup
rall_regress
second_anat+orig.HEAD
stim_AV1_vis.txt
stim_AV2_aud.txt
strip+orig.HEAD
```
... I see this doesn't contain either `epi_r1+orig.HEAD`, either.  Does that have to be added there separately?

Also, the testing hasn't complained about not finding `rall_vr+orig.BRIK`, but I also don't see `rall_vr+orig.HEAD` in that directory, either, so I wonder if that is another missing file we should add in the same way.

**Comment by yarikoptic** [comment]
> I feel sheepish for asking, but how should I do that here?

I do not remember details of your setup there -- I remember it was some adhoc dance with `rsync` etc and you had some notes somewhere. don't you?

but it seems that pretty much nothing is no longer provided by that `afni_ci_test_data` which is a location at https://afni.nimh.nih.gov/pub/dist/data/afni_ci_test_data/.git/ but from browser I cannot list that https://afni.nimh.nih.gov/pub/dist/data/afni_ci_test_data/.git/annex/ . Check what is happening on server (just ssh into it) -- may be you killed all files under there ?

**Comment by yarikoptic** [comment]
ah here all the instructions: https://github.com/afni/afni_ci_test_data/blob/HEAD/README.md#updating-sample-test-data . `rsync` memory was red-herring .  But again, since `git-annex` branch knows that file was there but now no longer there, something must have dropped it etc, so I would have first ssh'ed into that server location `afni.nimh.nih.gov:/fraid/pub/dist/data/afni_ci_test_data` and checked what is there under .git/annex/objects etc.

**Comment by yarikoptic** [comment]
woohoo -- we fixed testing with @afni-rickr 

![image](https://github.com/afni/afni/assets/39889/ecc83742-2eba-451b-bd6e-435bbc74c247)

it was just a matter of repopulating the annex of the afni_ci_test_data with needed files.  That macos_build fail due to some 

```
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at src/crorden/dcm2niix_console/ucm.cmake:13 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  src/crorden/dcm2niix_console/CMakeLists.txt:6 (include)


-- Performing Test ARM_CRC
-- Performing Test ARM_CRC - Failed
-- Performing Test HAS_SSE2
-- Performing Test HAS_SSE2 - Success
--   Adding Apple plist
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

CMake Error at src/python_scripts/CMakeLists.txt:38 (message):
  

        An error occurred when trying to find setuptools for
        the python interpreter:
        /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12
        You must install it if you wish to install ****py
        (or use a different python interpreter.


-- Configuring incomplete, errors occurred!
```

**Comment by afni-rickr** [comment]
Yes, thanks a lot @yarikoptic!!  It's nice to see that green checkmark again.  :)
On to the next issue...

**Comment by yarikoptic** [comment]
this was addressed in
- #656
